---
name: "Release"

on:
 push:
  branches:
   - "master"

jobs:
 GitHub:
  name: "Release - GitHub"
  runs-on: "ubuntu-latest"

  steps:
   - uses: actions/checkout@v2
   - name: "Install dependencies"
     run: |
      npm install

   - name: "Build"
     run: |
      npm run build

   - name: Zip Chrome extension
     uses: thedoctor0/zip-release@0.4.0
     with:
      filename: "chrome-extension.zip"
      path: "build/chrome"

   - name: Zip Firefox extension
     uses: thedoctor0/zip-release@0.4.0
     with:
      filename: "firefox-extension.zip"
      path: "build/firefox"

   - name: Draft release on GitHub
     uses: "marvinpinto/action-automatic-releases@latest"
     with:
      repo_token: "${{ secrets.GITHUB_TOKEN }}"
      automatic_release_tag: "latest"
      draft: true
      title: "Latest Release"
      files: |
       chrome-extension.zip
       firefox-extension.zip
